# Import libraries

In [1]:
import pandas as pd
import numpy as np

# RecipeNLG

In [2]:
df_recipe = pd.read_csv("dataset/recipenlg/full_dataset.csv")

In [3]:
df_recipe.head()

,Unnamed: 0,title,ingredients,directions,link,source,NER
0,0,No-Bake Nut Cookies,"[""1 c. firmly packed brown sugar"", ""1/2 c. eva...","[""In a heavy 2-quart saucepan, mix brown sugar...",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,"[""brown sugar"", ""milk"", ""vanilla"", ""nuts"", ""bu..."
1,1,Jewell Ball'S Chicken,"[""1 small jar chipped beef, cut up"", ""4 boned ...","[""Place chipped beef on bottom of baking dish....",www.cookbooks.com/Recipe-Details.aspx?id=699419,Gathered,"[""beef"", ""chicken breasts"", ""cream of mushroom..."
2,2,Creamy Corn,"[""2 (16 oz.) pkg. frozen corn"", ""1 (8 oz.) pkg...","[""In a slow cooker, combine all ingredients. C...",www.cookbooks.com/Recipe-Details.aspx?id=10570,Gathered,"[""frozen corn"", ""cream cheese"", ""butter"", ""gar..."
3,3,Chicken Funny,"[""1 large whole chicken"", ""2 (10 1/2 oz.) cans...","[""Boil and debone chicken."", ""Put bite size pi...",www.cookbooks.com/Recipe-Details.aspx?id=897570,Gathered,"[""chicken"", ""chicken gravy"", ""cream of mushroo..."
4,4,Reeses Cups(Candy),"[""1 c. peanut butter"", ""3/4 c. graham cracker ...","[""Combine first four ingredients and press in ...",www.cookbooks.com/Recipe-Details.aspx?id=659239,Gathered,"[""peanut butter"", ""graham cracker crumbs"", ""bu..."

In [4]:
df_recipe.tail()

,Unnamed: 0,title,ingredients,directions,link,source,NER
2231137,2231137,Sunny's Fake Crepes,"[""1/2 cup chocolate hazelnut spread (recommend...","[""Spread hazelnut spread on 1 side of each tor...",www.foodnetwork.com/recipes/sunny-anderson/sun...,Recipes1M,"[""chocolate hazelnut spread"", ""tortillas"", ""bu..."
2231138,2231138,Devil Eggs,"[""1 dozen eggs"", ""1 paprika"", ""1 salt and pepp...","[""Boil eggs on medium for 30mins."", ""Then cool...",cookpad.com/us/recipes/355411-devil-eggs,Recipes1M,"[""eggs"", ""paprika"", ""salt"", ""choice"", ""miracle..."
2231139,2231139,Extremely Easy and Quick - Namul Daikon Salad,"[""150 grams Daikon radish"", ""1 tbsp Sesame oil...","[""Julienne the daikon and squeeze out the exce...",cookpad.com/us/recipes/153324-extremely-easy-a...,Recipes1M,"[""radish"", ""Sesame oil"", ""White sesame seeds"",..."
2231140,2231140,Pan-Roasted Pork Chops With Apple Fritters,"[""1 cup apple cider"", ""6 tablespoons sugar"", ""...","[""In a large bowl, mix the apple cider with 4 ...",cooking.nytimes.com/recipes/1015164,Recipes1M,"[""apple cider"", ""sugar"", ""kosher salt"", ""bay l..."
2231141,2231141,Polpette in Spicy Tomato Sauce,"[""1 pound ground veal"", ""1/2 pound sweet Itali...","[""Preheat the oven to 350."", ""In a bowl, mix t...",www.foodandwine.com/recipes/polpette-spicy-tom...,Recipes1M,"[""ground veal"", ""sausage"", ""bread crumbs"", ""mi..."

In [8]:
df_recipe.shape, df_recipe.columns

((2231142, 7),
 Index(['Unnamed: 0', 'title', 'ingredients', 'directions', 'link', 'source',
        'NER'],
       dtype='str'))

In [10]:
df_recipe.describe(include='all')

,Unnamed: 0,title,ingredients,directions,link,source,NER
count,2.231142e+06,2231141,2231142,2231142,2231142,2231142,2231142
unique,NaN,1312870,2226362,2211644,2231142,2,2133496
top,NaN,Chicken Casserole,"[""1 c. peanut butter"", ""1 c. sugar"", ""1 egg""]","[""Mix all ingredients together.""]",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,[]
freq,NaN,4099,28,274,1,1643098,573
mean,1.115570e+06,NaN,NaN,NaN,NaN,NaN,NaN
std,6.440754e+05,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.577852e+05,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.115570e+06,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.673356e+06,NaN,NaN,NaN,NaN,NaN,NaN
max,2.231141e+06,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_recipe.info()

<class 'pandas.DataFrame'>
RangeIndex: 2231142 entries, 0 to 2231141
Data columns (total 7 columns):
 #   Column       Dtype
---  ------       -----
 0   Unnamed: 0   int64
 1   title        str
 2   ingredients  str
 3   directions   str
 4   link         str
 5   source       str
 6   NER          str
dtypes: int64(1), str(6)
memory usage: 119.2 MB

In [16]:
print(df_recipe.iloc[9]['NER'])

["pineapple", "condensed milk", "lemons", "pecans", "graham cracker crusts"]

In [17]:
print("\nCategorical description:\n", df_recipe.describe(include=['O']))

/tmp/ipykernel_2395/3008160897.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("\nCategorical description:\n", df_recipe.describe(include=['O']))

Categorical description:
                     title                                    ingredients  \
count             2231141                                        2231142
unique            1312870                                        2226362
top     Chicken Casserole  ["1 c. peanut butter", "1 c. sugar", "1 egg"]
freq                 4099                                             28

                               directions  \
count                             2231142
unique                            2211644
top     ["Mix all ingredients together."]
freq                                  274

                                                  link    source      NER
count                                          2231142   2231142  2231142
unique                                         2231142         2  2133496
top     www.cookbooks.com/Recipe-Details.aspx?id=44874  Gathered       []
freq                                                 1   1643098      573