# Import libraries

In [1]:
import pandas as pd
import numpy as np

# RecipeNLG

In [2]:
df_recipe = pd.read_csv("dataset/recipenlg/full_dataset.csv")

In [3]:
df_recipe.head()

,Unnamed: 0,title,ingredients,directions,link,source,NER
0,0,No-Bake Nut Cookies,"[""1 c. firmly packed brown sugar"", ""1/2 c. eva...","[""In a heavy 2-quart saucepan, mix brown sugar...",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,"[""brown sugar"", ""milk"", ""vanilla"", ""nuts"", ""bu..."
1,1,Jewell Ball'S Chicken,"[""1 small jar chipped beef, cut up"", ""4 boned ...","[""Place chipped beef on bottom of baking dish....",www.cookbooks.com/Recipe-Details.aspx?id=699419,Gathered,"[""beef"", ""chicken breasts"", ""cream of mushroom..."
2,2,Creamy Corn,"[""2 (16 oz.) pkg. frozen corn"", ""1 (8 oz.) pkg...","[""In a slow cooker, combine all ingredients. C...",www.cookbooks.com/Recipe-Details.aspx?id=10570,Gathered,"[""frozen corn"", ""cream cheese"", ""butter"", ""gar..."
3,3,Chicken Funny,"[""1 large whole chicken"", ""2 (10 1/2 oz.) cans...","[""Boil and debone chicken."", ""Put bite size pi...",www.cookbooks.com/Recipe-Details.aspx?id=897570,Gathered,"[""chicken"", ""chicken gravy"", ""cream of mushroo..."
4,4,Reeses Cups(Candy),"[""1 c. peanut butter"", ""3/4 c. graham cracker ...","[""Combine first four ingredients and press in ...",www.cookbooks.com/Recipe-Details.aspx?id=659239,Gathered,"[""peanut butter"", ""graham cracker crumbs"", ""bu..."

In [4]:
df_recipe.tail()

,Unnamed: 0,title,ingredients,directions,link,source,NER
2231137,2231137,Sunny's Fake Crepes,"[""1/2 cup chocolate hazelnut spread (recommend...","[""Spread hazelnut spread on 1 side of each tor...",www.foodnetwork.com/recipes/sunny-anderson/sun...,Recipes1M,"[""chocolate hazelnut spread"", ""tortillas"", ""bu..."
2231138,2231138,Devil Eggs,"[""1 dozen eggs"", ""1 paprika"", ""1 salt and pepp...","[""Boil eggs on medium for 30mins."", ""Then cool...",cookpad.com/us/recipes/355411-devil-eggs,Recipes1M,"[""eggs"", ""paprika"", ""salt"", ""choice"", ""miracle..."
2231139,2231139,Extremely Easy and Quick - Namul Daikon Salad,"[""150 grams Daikon radish"", ""1 tbsp Sesame oil...","[""Julienne the daikon and squeeze out the exce...",cookpad.com/us/recipes/153324-extremely-easy-a...,Recipes1M,"[""radish"", ""Sesame oil"", ""White sesame seeds"",..."
2231140,2231140,Pan-Roasted Pork Chops With Apple Fritters,"[""1 cup apple cider"", ""6 tablespoons sugar"", ""...","[""In a large bowl, mix the apple cider with 4 ...",cooking.nytimes.com/recipes/1015164,Recipes1M,"[""apple cider"", ""sugar"", ""kosher salt"", ""bay l..."
2231141,2231141,Polpette in Spicy Tomato Sauce,"[""1 pound ground veal"", ""1/2 pound sweet Itali...","[""Preheat the oven to 350."", ""In a bowl, mix t...",www.foodandwine.com/recipes/polpette-spicy-tom...,Recipes1M,"[""ground veal"", ""sausage"", ""bread crumbs"", ""mi..."

In [8]:
df_recipe.shape, df_recipe.columns

((2231142, 7),
 Index(['Unnamed: 0', 'title', 'ingredients', 'directions', 'link', 'source',
        'NER'],
       dtype='str'))

In [10]:
df_recipe.describe(include='all')

,Unnamed: 0,title,ingredients,directions,link,source,NER
count,2.231142e+06,2231141,2231142,2231142,2231142,2231142,2231142
unique,NaN,1312870,2226362,2211644,2231142,2,2133496
top,NaN,Chicken Casserole,"[""1 c. peanut butter"", ""1 c. sugar"", ""1 egg""]","[""Mix all ingredients together.""]",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,[]
freq,NaN,4099,28,274,1,1643098,573
mean,1.115570e+06,NaN,NaN,NaN,NaN,NaN,NaN
std,6.440754e+05,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.577852e+05,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.115570e+06,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.673356e+06,NaN,NaN,NaN,NaN,NaN,NaN
max,2.231141e+06,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_recipe.info()

<class 'pandas.DataFrame'>
RangeIndex: 2231142 entries, 0 to 2231141
Data columns (total 7 columns):
 #   Column       Dtype
---  ------       -----
 0   Unnamed: 0   int64
 1   title        str
 2   ingredients  str
 3   directions   str
 4   link         str
 5   source       str
 6   NER          str
dtypes: int64(1), str(6)
memory usage: 119.2 MB

In [16]:
print(df_recipe.iloc[9]['NER'])

["pineapple", "condensed milk", "lemons", "pecans", "graham cracker crusts"]

In [17]:
print("\nCategorical description:\n", df_recipe.describe(include=['O']))

/tmp/ipykernel_2395/3008160897.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("\nCategorical description:\n", df_recipe.describe(include=['O']))

Categorical description:
                     title                                    ingredients  \
count             2231141                                        2231142
unique            1312870                                        2226362
top     Chicken Casserole  ["1 c. peanut butter", "1 c. sugar", "1 egg"]
freq                 4099                                             28

                               directions  \
count                             2231142
unique                            2211644
top     ["Mix all ingredients together."]
freq                                  274

                                                  link    source      NER
count                                          2231142   2231142  2231142
unique                                         2231142         2  2133496
top     www.cookbooks.com/Recipe-Details.aspx?id=44874  Gathered       []
freq                                                 1   1643098      573

# Food.com recipes

In [3]:
df_raw_recipes = pd.read_csv("/home/ahmad/bootdev/recipe_generator/dataset/food_com/RAW_recipes.csv")

In [4]:
df_raw_interactions = pd.read_csv("/home/ahmad/bootdev/recipe_generator/dataset/food_com/RAW_interactions.csv")

In [5]:
df_raw_recipes.head()

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [7]:
df_raw_interactions.head()

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

# Multi-cuisine dataset

In [3]:
df = pd.read_csv("./dataset/Multi_Cuisine_Recipe_Dataset.csv")

In [4]:
df.head()

,name,area,category,ingredients,steps
0,Hyderabad Soy Biryani With Vegetables & Palak,Indian,Main Course,"2 cups Basmati rice - soaked for 30 minutes,8 ...",To begin making Hyderabad Soy Biryani Recipe W...
1,Sagu Masala Dosa,Indian,South Indian Breakfast,"3/4 cup White Urad Dal (Split),1 cup Red matta...",*To Prepare the Dosa batterTo begin making the...
2,Chicken Burrito,Indian,Lunch,"300 grams Chicken - cut into stripes,1 Onion -...","To begin making the Chicken Burrito Recipe, we..."
3,Matar Paneer Kachori Korma - Green Peas And P...,Indian,Lunch,"1 cup All Purpose Flour (Maida),2 tablespoons ...",To begin making the Matar Paneer Kachori Korma...
4,Raw Jackfruit Burrito,Indian,Lunch,200 grams Jackfruit Raw (Kathal) - peeled and ...,To make the refried beansTo begin making the R...

In [5]:
df.describe(include='all')

,name,area,category,ingredients,steps
count,620,620,620,620,620
unique,619,13,24,620,619
top,Vegan Navratan Korma,Indian,Dessert,"2 cups Basmati rice - soaked for 30 minutes,8 ...","Heat the flat grill plate over a low heat, on ..."
freq,2,200,107,1,2

In [6]:
df['ingredients'][0]

'2 cups Basmati rice - soaked for 30 minutes,8 cups Water,Salt - to taste,1/4 cup Soy Chunks (Nuggets) - soaked in hot water for 15 minutes,1/4 cup Carrots (Gajjar) - chopped,1/4 cup Green beans (French Beans) - chopped,1/4 cup Green peas (Matar),1/4 cup Cauliflower (gobi) - chopped,1/4 cup Green Bell Pepper (Capsicum) - chopped,3 Potatoes (Aloo) - cubed,2 Tomatoes - chopped,4 Onions - chopped,2 tablespoons Ginger Garlic Paste,Sunflower Oil - to cook,1 inch Cinnamon Stick (Dalchini),1 Cardamom (Elaichi) Pods/Seeds,1 Cloves (Laung),1/4 teaspoon Cumin seeds (Jeera),1-1/2 cups Spinach Leaves (Palak) - or 1 bunch,1/2 cup Coriander (Dhania) Leaves,1/2 cup Mint Leaves (Pudina),3 Green Chillies,5 Badam (Almond),2 inch Cinnamon Stick (Dalchini),3 Cardamom (Elaichi) Pods/Seeds,1 Black cardamom (Badi Elaichi),3 Cloves (Laung),1 Bay leaf (tej patta),1/2 teaspoon Ajwain (Carom seeds),1/4 Mace (Javitri),1/2 teaspoon Turmeric powder (Haldi),1 teaspoon Red Chilli powder,1-1/2 teaspoon Coriander Powder (Dhania),2 teaspoon Garam masala powder,Salt - to taste,2 cups Onions - sliced,1/4 cup Coriander (Dhania) Leaves - chopped,1/4 cup Mint Leaves (Pudina) - roughly torn,1/2 cup Milk,7 Saffron strands,Ghee - as needed'

In [7]:
df.columns

Index(['name', 'area', 'category', 'ingredients', 'steps'], dtype='str')